CREATE DATABASE curso_sql;

USE curso_sql;

CREATE TABLE funcionario
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nome VARCHAR(45) NOT NULL,
    salario DOUBLE NOT NULL DEFAULT '0',
    departamento VARCHAR(45) NOT NULL,
    PRIMARY KEY(id)
);

SELECT * FROM funcionarios;

CREATE TABLE veiculo
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	funcionario_id INT UNSIGNED DEFAULT NULL,
    veiculo VARCHAR(45) NOT NULL DEFAULT '',
    placa VARCHAR(10) NOT NULL DEFAULT '',
    PRIMARY KEY(id),
    CONSTRAINT fk_veiculo_funcionario FOREIGN KEY(funcionario_id)
    REFERENCES funcionario (ID)
);

SELECT * FROM veiculo;

CREATE TABLE salario
(
	faixa VARCHAR(45) NOT NULL,
    inicio DOUBLE NOT NULL,
    fim DOUBLE NOT NULL,
    PRIMARY KEY (faixa)
);

-- NESTE BANCO DE DADOS TUDO ESTÁ RELACIONADO COM CHAVES PRIMÁRIAS E ESTRANGEIRAS
-- DE ACORDO COM O QUE PERTENCE A QUEM
-- VEÍCULOS PERTENCEM A FUNCIONÁRIOS // FUNCIONÁRIOS TÊM SALÁRIOS // ETC